### ISSUE TITLE
error on running hls

### ISSUE THREAD

**Issue by feiziDerakhshi** [samuelgarcia/HearingLossSimulator#4]
After successful installation try to run by "hls", That i get this errors:::

D:\HearingLossSimulator>hls

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\sounddevice-0.3.12-py3.6.egg\sounddevice.py", line 71, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\hls-script.py", line 11, in <module>
    load_entry_point('hearinglosssimulator==1.0.0.dev0', 'console_scripts', 'hls')()
  File "C:\ProgramData\Anaconda3\lib\site-packages\hearinglosssimulator-1.0.0.dev0-py3.6.egg\hearinglosssimulator\scripts.py", line 90, in hls
    open_audiodevice_mainwindow()
  File "C:\ProgramData\Anaconda3\lib\site-packages\hearinglosssimulator-1.0.0.dev0-py3.6.egg\hearinglosssimulator\scripts.py", line 24, in open_audiodevice_mainwindow
    from hearinglosssimulator.gui.audiodevice_mainwindow import AudioDeviceMainWindow
  File "C:\ProgramData\Anaconda3\lib\site-packages\hearinglosssimulator-1.0.0.dev0-py3.6.egg\hearinglosssimulator\gui\audiodevice_mainwindow.py", line 1, in <module>
    from .common_mainwindow import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\hearinglosssimulator-1.0.0.dev0-py3.6.egg\hearinglosssimulator\gui\common_mainwindow.py", line 10, in <module>
    import sounddevice as sd
  File "C:\ProgramData\Anaconda3\lib\site-packages\sounddevice-0.3.12-py3.6.egg\sounddevice.py", line 80, in <module>
    import _sounddevice_data
ModuleNotFoundError: No module named '_sounddevice_data'

**Comment by samuelgarcia** [comment]
This is a problem of sounddevice install.

could you try to install it with conda rahter than pip:
```
pip uninstall sounddevice
conda install -c conda-forge python-sounddevice
```
