### ISSUE TITLE
pyopencl._cl.LogicError: clEnqueueNDRangeKernel failed: INVALID_WORK_ITEM_SIZE

### ISSUE THREAD

**Issue by AudifyUK** [samuelgarcia/HearingLossSimulator#6]
Using offline_wav_file.py results in the following error, running Python 3.8 on Mac OS 10.15.7, and applied to a 32-bit float WAV file, stereo 44100Hz:

----------------------
Traceback (most recent call last):
  File "/Users/xxxxx/Documents/Other Software/HearingLossSimulator-master/examples/offline_wav_file.py", line 32, in <module>
    hls.compute_wave_file(in_filename, out_filename, processing_class=hls.InvComp, duration_limit=None, 
  File "/Users/xxxxx/opt/anaconda3/lib/python3.8/site-packages/hearinglosssimulator/offlinehelper.py", line 207, in compute_wave_file
    for i, returns in enumerate(loop()):
  File "/Users/xxxxx/opt/anaconda3/lib/python3.8/site-packages/hearinglosssimulator/offlinehelper.py", line 44, in loop
    returns = processing.proccesing_func(index, in_chunk)
  File "/Users/xxxxx/opt/anaconda3/lib/python3.8/site-packages/hearinglosssimulator/invcomp.py", line 217, in proccesing_func
    event = self.kern_sos_filter(self.queue, global_size, local_size,
  File "/Users/xxxxx/opt/anaconda3/lib/python3.8/site-packages/pyopencl/__init__.py", line 880, in kernel_call
    return self._enqueue(self, queue, global_size, local_size, *args, **kwargs)
  File "<generated code>", line 98, in enqueue_knl_sos_filter
pyopencl._cl.LogicError: clEnqueueNDRangeKernel failed: INVALID_WORK_ITEM_SIZE
----------------------

The cache for filters InvComp seems to be successfully generated, the new .WAV file is generated, but the .WAV file is empty.

**Comment by samuelgarcia** [comment]
It seems that you have an opencl installation problem.
Can you do:
```
import pyopencl
print(pyopencl.get_platforms())
```

**Comment by AudifyUK** [comment]
> It seems that you have an opencl installation problem.
> Can you do:
> 
> ```
> import pyopencl
> print(pyopencl.get_platforms())
> ```

This code returns:

[<pyopencl.Platform 'Apple' at 0x7ff2afc14810>]

**Comment by samuelgarcia** [comment]
So it is a bug in HLS.
How many bands are you using ?

**Comment by AudifyUK** [comment]
I was just using the default example code for offline processing.

Do you have an audio-file you that know works that we could test it with? That way we could rule out variations in the format of the audio-file and perhaps narrow down where it's stalling?

**Comment by DFuller134** [comment]
I am having the same issue on Apple:

import pyopencl
print(pyopencl.get_platforms())

[<pyopencl.Platform 'Apple' at 0x7fff0000>]

Newer versions of MacOS use Metal. Could this be an OpenCL backward compatibility issue?

**Comment by ArmandSchwarz** [comment]
Hello 
I have the same issue, using a mac M1, I just installed the hls from ur page. Did u find a solution?

Thanks a lot

**Comment by ArmandSchwarz** [comment]
I have found the answer : fix gpu_platform_index=0 and gpu_device_index=1
