### ISSUE TITLE
HLS gui crashes when "Test Input to Output" (under Configure Audio menu)

### ISSUE THREAD

**Issue by AudifyUK** [samuelgarcia/HearingLossSimulator#7]
Running Python 3.8 on Mac OS 10.15.7, sounddevice 0.4.1, PyOpenCl 2020.3.1:

-------------------------
Traceback (most recent call last):
  File "/Users/xxxxx/opt/anaconda3/lib/python3.8/site-packages/hearinglosssimulator/gui/audioselection.py", line 99, in play_input_to_output
    play_input_to_output(duration, device, sample_rate=44100, chunksize=1024, nb_channel=2)
  File "/Users/xxxxx/opt/anaconda3/lib/python3.8/site-packages/hearinglosssimulator/gui/guitools.py", line 104, in play_input_to_output
    dev = sd.query_devices(device=device)
  File "/Users/xxxxx/opt/anaconda3/lib/python3.8/site-packages/sounddevice.py", line 561, in query_devices
    device = _get_device_id(device, kind, raise_on_error=True)
  File "/Users/xxxxx/opt/anaconda3/lib/python3.8/site-packages/sounddevice.py", line 2757, in _get_device_id
    raise ValueError('Input and output device are different: {!r}'
ValueError: Input and output device are different: ('MacBook Pro Microphone', 'MacBook Pro Speakers')
Abort trap: 6
-------------------------

I don't know whether it's related... on the GUI, the "Start/Stop playback" and "Enable/bypass simulator" are both greyed out.

**Comment by samuelgarcia** [comment]
You need to select an input<->oupt audio pair that is compatible (same engine, same number of channel same sampling rate...)

**Comment by AudifyUK** [comment]
Input audio defaults to the MacBook's built-in microphone (single channel?), and the output is the speaker's on the MacBook (two channel, stereo?). 

Do you have a recommendation for what to use instead? I'm assuming the software works by converting a microphone signal to the simulated hearing loss signal on the fly? So would a wireless headset work best?

**Comment by samuelgarcia** [comment]
If input is mono and output stereo then the HLS will bug.
It is not handle yet unfortunatly.
I should do it but won't have time soon.
